3060 toolbar menu mui 5 styled
brightlayer-ui/react-component-library pull request #416
Opened 2022-04-28 15:18 UTC by jeffvg

Fixes # .

#### Changes proposed in this Pull Request:
- Update to use Mui-v5 styled components
- Update component to extend sx prop
- Update component docs for ToolbarMenu

**Also would like a suggestion on an example code snippet for this in the docs

#### Screenshots:
Temporary ToolbarMenu
![image](https://user-images.githubusercontent.com/37150565/165996403-70e5f47a-9ab6-49c3-8de3-b269d47cae99.png)

#### To Test:
- There is a showcase branch [feature/3050-channel-value-mui-v5-styles-update](https://github.com/brightlayer-ui/react-showcase-demo/tree/feature/3050-channel-value-mui-v5-styles-update) that this can be tested in the ```SharedAppBar```

```
                 <ToolbarMenu
                    label={'Toolbar-menu'}
                    menuGroups={menuGroups}
                    // style={{ backgroundColor: '#ffbb00' }} // specificity 1
                    classes={{ rotatedDropdownArrow: classes.green }} // specificity 2
                    // className={classes.blue} // specificity 3
                    sx={{ backgroundColor: '#bb00ff' }} // specificity 4
                ></ToolbarMenu>
```

Ensure that there are no breaking changes and that the old API properties still work the same and that you can still style inline styles using our classes prop.
Test sx prop extension.

2022-05-02 05:10 UTC, bkarambe requested changes

2022-05-02 12:14 UTC, daileytj commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
> +    slot: 'arrow-drop-down',
That's not exactly how that works and it doesn't have to be one of the slots previously defined. However, we should standardize how we are naming these. I've been sticking with kebab-case like I would with html classes.

2022-05-02 12:14 UTC, daileytj commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
> +    slot: 'nav-groups',
same refute as above...

2022-05-02 12:16 UTC, daileytj commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
> +        ...otherTypographyProps
I prefer to have the explicit typography name in here since the remaining props are indeed typography props

2022-05-02 12:16 UTC, daileytj commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
>                  {...otherTypographyProps}
I prefer to have the explicit typography name in here since the remaining props are indeed typography props

2022-05-02 12:18 UTC, daileytj commented
@bkarambe, when you are going to be off for some time can you please add your comments and suggestions without blocking the PR with a change request?

2022-05-02 13:26 UTC, jeffvg commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
> +    slot: 'arrow-drop-down',
change this to drop-down-arrow?

2022-05-02 13:27 UTC, jeffvg commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
> +    slot: 'nav-groups',
this matches what we defined for slot, should this be changed?

2022-05-02 14:57 UTC, emclaug2 commented
> @bkarambe, when you are going to be off for some time can you please add your comments and suggestions without blocking the PR with a change request?

If Suraj is out tomorrow & this PR is adjusted by end of day, might be easier to re-open the PR to move it along.

2022-05-02 15:30 UTC, jeffvg commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
> +    slot: 'nav-groups',
not sure what to do here. Leave dashes or match one-to-one

2022-05-02 17:48 UTC, daileytj commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
> +    slot: 'nav-groups',
Leave dashes for the styled components for now. We honestly don't even need to use name and slot here. We should revisit the standard for how we do all of these another time.

2022-05-02 17:49 UTC, daileytj commented on components/src/core/ToolbarMenu/ToolbarMenu.tsx
> +    slot: 'arrow-drop-down',
may be worthwhile to rename this one to `drop-down-arrow` as you suggested

2022-05-03 12:51 UTC, daileytj approved these changes

2022-05-03 13:15 UTC, merged