Feature/channel value playground
brightlayer-ui/react-component-library pull request #530
Opened 2022-09-15 16:40 UTC by ektasawant

Fixes 3502 .

#### Changes proposed in this Pull Request:
- Update channelValue playground
- Fix copy all button from playground snippet

#### Screenshots:

#### To Test:
- http://localhost:3000/components/channel-value/playground

2022-09-15 18:56 UTC, huayunh requested changes
`unitSpace` is actually not required. Would you update both API Table and Playground to reflect this?

Things look good otherwise.

2022-09-16 06:03 UTC, ektasawant commented
> `unitSpace` is actually not required. Would you update both API Table and Playground to reflect this?
> 
> Things look good otherwise.

We have this prop inside channelValue component. https://github.com/brightlayer-ui/react-component-library/blob/dev/components/src/core/ChannelValue/ChannelValue.tsx#L57. Any specific reason to remove it from API docs and playground?

2022-09-16 06:48 UTC, huayunh commented
Not to remove it, but to update the API table so that it does not say unitSpace is required

2022-09-16 08:11 UTC, ektasawant commented
> Not to remove it, but to update the API table so that it does not say unitSpace is required

Oops now I understand . Let me update.

2022-09-16 08:23 UTC, ektasawant commented
> https://blui-react-docs--pr530-feature-channel-valu-om8r7o61.web.app

<img width="1274" alt="Screenshot 2022-09-16 at 1 53 10 PM" src="https://user-images.githubusercontent.com/10433274/190592391-de0cd198-85b1-438d-8758-b5e7b60e3402.png">
<img width="376" alt="Screenshot 2022-09-16 at 1 53 23 PM" src="https://user-images.githubusercontent.com/10433274/190592403-d7de6709-a186-4ccd-9584-a76aba0add24.png">

Done.

2022-09-16 08:26 UTC, merged

2022-09-16 08:27 UTC, ektasawant commented
> `unitSpace` is actually not required. Would you update both API Table and Playground to reflect this?
> 
> Things look good otherwise.

Merged this story.

2022-09-16 08:33 UTC, huayunh reviewed
lgtm

(didn't check code)