update blui-3525 spacer
brightlayer-ui/react-component-library pull request #585
Opened 2022-10-06 16:31 UTC by jeffvg

Fixes # .

#### Changes proposed in this Pull Request:
- update examples to use sx

#### Screenshots:
![image](https://user-images.githubusercontent.com/37150565/194379470-7aef24ae-0357-4c2b-9259-ee1af398c64a.png)

#### To Test:
- yarn start:reactdev or visit deployed link

2022-10-06 16:32 UTC, emclaug2 approved these changes

2022-10-06 16:39 UTC, huayunh requested changes
that "Spacer with Pixels" horizontal spacer example still looks off, according to your screenshot

2022-10-06 16:39 UTC, huayunh commented on docs/src/componentDocs/Spacer/examples/SpacerWithPixel.tsx
>      </Box>
Try this

```suggestion
<Box sx={{ height: '56px' }}>
        <Spacer width={25} sx={{ backgroundColor: '#4da3d4' }}>25</Spacer>
        <Spacer width={75} sx={{ backgroundColor: '#f5db6d' }}>75</Spacer>
        <Spacer width={200} sx={{ backgroundColor: '#da7777' }}>200</Spacer>
 </Box>
```

2022-10-07 03:25 UTC, huayunh approved these changes

2022-10-07 03:25 UTC, merged